/** Operational Indian airports with IATA (DGCA / AAI list). */
export type IndiaAirport = { city: string; iata: string; name: string };

export const GOA_DEST_IATA = "GOI" as const;

export const INDIA_AIRPORTS: IndiaAirport[] = [
  { city: "Agartala", iata: "IXA", name: "Maharaja Bir Bikram Airport" },
  { city: "Agatti Island", iata: "AGX", name: "Agatti Airport" },
  { city: "Agra", iata: "AGR", name: "Agra Airport" },
  { city: "Ahmedabad", iata: "AMD", name: "Sardar Vallabhbhai Patel International Airport" },
  { city: "Aizawl", iata: "AJL", name: "Lengpui Airport" },
  { city: "Ajmer", iata: "KQH", name: "Kishangarh Airport" },
  { city: "Aligarh", iata: "HRH", name: "Aligarh Airport" },
  { city: "Ambikapur", iata: "AHA", name: "Ambikapur Airport" },
  { city: "Amravati", iata: "AVR", name: "Amravati Airport" },
  { city: "Amritsar", iata: "ATQ", name: "Sri Guru Ram Dass Jee International Airport" },
  { city: "Aurangabad", iata: "IXU", name: "Aurangabad Airport" },
  { city: "Ayodhya", iata: "AYJ", name: "Maharishi Valmiki International Airport" },
  { city: "Azamgarh", iata: "AZH", name: "Azamgarh Airport" },
  { city: "Ballari", iata: "VDY", name: "Jindal Vijaynagar Airport" },
  { city: "Bareilly", iata: "BEK", name: "Bareilly Airport" },
  { city: "Bathinda", iata: "BUP", name: "Bathinda Airport" },
  { city: "Belagavi", iata: "IXG", name: "Belagavi Airport" },
  { city: "Bengaluru", iata: "BLR", name: "Kempegowda International Airport" },
  { city: "Bhavnagar", iata: "BHU", name: "Bhavnagar Airport" },
  { city: "Bhopal", iata: "BHO", name: "Raja Bhoj Airport" },
  { city: "Bhubaneswar", iata: "BBI", name: "Biju Patnaik Airport" },
  { city: "Bhuj", iata: "BHJ", name: "Bhuj Airport" },
  { city: "Bidar", iata: "IXX", name: "Bidar Airport" },
  { city: "Bikaner", iata: "BKB", name: "Bikaner Airport" },
  { city: "Bilaspur", iata: "PAB", name: "Bilasa Devi Kevat Airport" },
  { city: "Chandigarh", iata: "IXC", name: "Shaheed Bhagat Singh International Airport" },
  { city: "Chennai", iata: "MAA", name: "Chennai International Airport" },
  { city: "Chitrakoot", iata: "CWK", name: "Chitrakoot Airport" },
  { city: "Coimbatore", iata: "CJB", name: "Coimbatore International Airport" },
  { city: "Cooch Behar", iata: "COH", name: "Cooch Behar Airport" },
  { city: "Dabolim", iata: "GOI", name: "Dabolim Airport" },
  { city: "Daman", iata: "NMB", name: "Daman Airport" },
  { city: "Darbhanga", iata: "DBR", name: "Darbhanga Airport" },
  { city: "Datia", iata: "DPP", name: "Datia Airport" },
  { city: "Dehradun", iata: "DED", name: "Jolly Grant Airport" },
  { city: "Delhi NCR", iata: "DEL", name: "Indira Gandhi International Airport" },
  { city: "Deoghar", iata: "DGH", name: "Deoghar Airport" },
  { city: "Dhubri", iata: "RUP", name: "Rupsi Airport" },
  { city: "Dibrugarh", iata: "DIB", name: "Dibrugarh Airport" },
  { city: "Dimapur", iata: "DMU", name: "Dimapur Airport" },
  { city: "Diu", iata: "DIU", name: "Diu Airport" },
  { city: "Durgapur", iata: "RDP", name: "Kazi Nazrul Islam Airport" },
  { city: "Gangtok", iata: "PYG", name: "Pakyong Airport" },
  { city: "Gaya", iata: "GAY", name: "Gaya Airport" },
  { city: "Ghaziabad", iata: "HDO", name: "Hindon Airport" },
  { city: "Gondia", iata: "GDB", name: "Gondia Airport" },
  { city: "Gorakhpur", iata: "GOP", name: "Gorakhpur Airport" },
  { city: "Guwahati", iata: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport" },
  { city: "Gwalior", iata: "GWL", name: "Rajmata Vijaya Raje Scindia Airport" },
  { city: "Hisar", iata: "HSS", name: "Hisar Airport" },
  { city: "Hubli", iata: "HBX", name: "Hubli Airport" },
  { city: "Hyderabad", iata: "BPM", name: "Begumpet Airport" },
  { city: "Hyderabad", iata: "HYD", name: "Rajiv Gandhi International Airport" },
  { city: "Imphal", iata: "IMF", name: "Bir Tikendrajit International Airport" },
  { city: "Indore", iata: "IDR", name: "Devi Ahilyabai Holkar Airport" },
  { city: "Itanagar", iata: "HGI", name: "Donyi Polo Airport" },
  { city: "Jabalpur", iata: "JLR", name: "Jabalpur Airport" },
  { city: "Jagdalpur", iata: "JGB", name: "Jagdalpur Airport" },
  { city: "Jaipur", iata: "JAI", name: "Jaipur International Airport" },
  { city: "Jaisalmer", iata: "JSA", name: "Jaisalmer Airport" },
  { city: "Jalandhar", iata: "AIP", name: "Sri Guru Ravidas Airport" },
  { city: "Jalgaon", iata: "JLG", name: "Jalgaon Airport" },
  { city: "Jammu", iata: "IXJ", name: "Jammu Airport" },
  { city: "Jamnagar", iata: "JGA", name: "Jamnagar Airport" },
  { city: "Jamshedpur", iata: "IXW", name: "Sonari Airport" },
  { city: "Jeypore", iata: "PYB", name: "Jeypore Airport" },
  { city: "Jharsuguda", iata: "JRG", name: "Veer Surendra Sai Airport" },
  { city: "Jodhpur", iata: "JDH", name: "Jodhpur Airport" },
  { city: "Jorhat", iata: "JRH", name: "Jorhat Airport" },
  { city: "Junagadh", iata: "IXK", name: "Keshod Airport" },
  { city: "Kadapa", iata: "CDP", name: "Kadapa Airport" },
  { city: "Kalaburagi", iata: "GBI", name: "Kalaburagi Airport" },
  { city: "Kandla", iata: "IXY", name: "Kandla Airport" },
  { city: "Kangra", iata: "DHM", name: "Kangra Airport" },
  { city: "Kannur", iata: "CNN", name: "Kannur International Airport" },
  { city: "Kanpur", iata: "KNU", name: "Kanpur Airport" },
  { city: "Khajuraho", iata: "HJR", name: "Khajuraho Airport" },
  { city: "Kochi", iata: "COK", name: "Cochin International Airport" },
  { city: "Kolhapur", iata: "KLH", name: "Kolhapur Airport" },
  { city: "Kolkata", iata: "CCU", name: "Netaji Subhas Chandra Bose International Airport" },
  { city: "Kota", iata: "KTU", name: "Kota Airport" },
  { city: "Kozhikode", iata: "CCJ", name: "Kozhikode International Airport" },
  { city: "Kullu-Manali", iata: "KUU", name: "Kullu–Manali Airport" },
  { city: "Kurnool", iata: "KJB", name: "Kurnool Airport" },
  { city: "Kushinagar", iata: "KBK", name: "Kushinagar International Airport" },
  { city: "Leh", iata: "IXL", name: "Kushok Bakula Rimpochee Airport" },
  { city: "Lucknow", iata: "LKO", name: "Chaudhary Charan Singh International Airport" },
  { city: "Ludhiana", iata: "HWR", name: "Halwara Airport" },
  { city: "Ludhiana", iata: "LUH", name: "Ludhiana Airport" },
  { city: "Madurai", iata: "IXM", name: "Madurai International Airport" },
  { city: "Mangaluru", iata: "IXE", name: "Mangaluru International Airport" },
  { city: "Mopa", iata: "GOX", name: "Manohar International Airport" },
  { city: "Moradabad", iata: "MZS", name: "Moradabad Airport" },
  { city: "Mumbai", iata: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport" },
  { city: "Mundra", iata: "MDA", name: "Mundra Airport" },
  { city: "Mysuru", iata: "MYQ", name: "Mysuru Airport" },
  { city: "Nagpur", iata: "NAG", name: "Dr. Babasaheb Ambedkar International Airport" },
  { city: "Nanded", iata: "NDC", name: "Shri Guru Gobind Singh Ji Airport" },
  { city: "Nashik", iata: "ISK", name: "Nashik Airport" },
  { city: "Navi Mumbai", iata: "NMI", name: "Navi Mumbai International Airport" },
  { city: "Noida", iata: "DXN", name: "Noida International Airport" },
  { city: "North Lakhimpur", iata: "IXI", name: "Lilabari Airport" },
  { city: "Pantnagar", iata: "PGH", name: "Pantnagar Airport" },
  { city: "Pasighat", iata: "IXT", name: "Pasighat Airport" },
  { city: "Patna", iata: "PAT", name: "Jay Prakash Narayan Airport" },
  { city: "Pithoragarh", iata: "NNS", name: "Naini-Saini Airport" },
  { city: "Porbandar", iata: "PBD", name: "Porbandar Airport" },
  { city: "Port Blair", iata: "IXZ", name: "Veer Savarkar International Airport" },
  { city: "Prayagraj", iata: "IXD", name: "Prayagraj Airport" },
  { city: "Puducherry", iata: "PNY", name: "Puducherry Airport" },
  { city: "Pune", iata: "PNQ", name: "Pune Airport" },
  { city: "Purnia", iata: "PXN", name: "Purnia Airport" },
  { city: "Puttaparthi", iata: "PUT", name: "Sri Sathya Sai Airport" },
  { city: "Raipur", iata: "RPR", name: "Swami Vivekananda Airport" },
  { city: "Rajahmundry", iata: "RJA", name: "Rajahmundry Airport" },
  { city: "Rajkot", iata: "HSR", name: "Rajkot International Airport" },
  { city: "Ranchi", iata: "IXR", name: "Birsa Munda Airport" },
  { city: "Rewa", iata: "REW", name: "Rewa Airport" },
  { city: "Rourkela", iata: "RRK", name: "Rourkela Airport" },
  { city: "Salem", iata: "SXV", name: "Salem Airport" },
  { city: "Satna", iata: "TNI", name: "Satna Airport" },
  { city: "Shillong", iata: "SHL", name: "Shillong Airport" },
  { city: "Shimla", iata: "SLV", name: "Shimla Airport" },
  { city: "Shirdi", iata: "SAG", name: "Shirdi Airport" },
  { city: "Shivamogga", iata: "RQY", name: "Rashtrakavi Kuvempu Airport" },
  { city: "Shravasti", iata: "VSV", name: "Shravasti Airport" },
  { city: "Silchar", iata: "IXS", name: "Silchar Airport" },
  { city: "Siliguri", iata: "IXB", name: "Bagdogra International Airport" },
  { city: "Sindhudurg", iata: "SDW", name: "Sindhudurg Airport" },
  { city: "Solapur", iata: "SSE", name: "Solapur Airport" },
  { city: "Srinagar", iata: "SXR", name: "Srinagar International Airport" },
  { city: "Surat", iata: "STV", name: "Surat International Airport" },
  { city: "Tezpur", iata: "TEZ", name: "Tezpur Airport" },
  { city: "Tezu", iata: "TEI", name: "Tezu Airport" },
  { city: "Thiruvananthapuram", iata: "TRV", name: "Thiruvananthapuram International Airport" },
  { city: "Thoothukkudi", iata: "TCR", name: "Thoothukudi Airport" },
  { city: "Tiruchirappalli", iata: "TRZ", name: "Tiruchirappalli International Airport" },
  { city: "Tirupati", iata: "TIR", name: "Tirupati Airport" },
  { city: "Udaipur", iata: "UDR", name: "Maharana Pratap Airport" },
  { city: "Utkela", iata: "UKE", name: "Utkela Airport" },
  { city: "Vadodara", iata: "BDQ", name: "Vadodara Airport" },
  { city: "Varanasi", iata: "VNS", name: "Lal Bahadur Shastri Airport" },
  { city: "Vijayawada", iata: "VGA", name: "Vijayawada International Airport" },
  { city: "Visakhapatnam", iata: "VTZ", name: "Visakhapatnam Airport" },
  { city: "Ziro", iata: "ZER", name: "Ziro Airport" },
];

export function searchIndiaAirports(query: string, limit = 12): IndiaAirport[] {
  const q = query.trim().toLowerCase();
  if (!q) return INDIA_AIRPORTS.slice(0, limit);
  const scored = INDIA_AIRPORTS.map((a) => {
    const city = a.city.toLowerCase();
    const iata = a.iata.toLowerCase();
    const name = a.name.toLowerCase();
    let score = 0;
    if (iata === q) score = 100;
    else if (iata.startsWith(q)) score = 90;
    else if (city.startsWith(q)) score = 80;
    else if (city.includes(q)) score = 60;
    else if (name.includes(q)) score = 40;
    else if (iata.includes(q)) score = 30;
    return { a, score };
  }).filter((x) => x.score > 0);
  scored.sort((x, y) => y.score - x.score || x.a.city.localeCompare(y.a.city));
  return scored.slice(0, limit).map((x) => x.a);
}

export function formatAirportLabel(a: IndiaAirport): string {
  return `${a.iata} · ${a.city}`;
}
